## Chapter 11. 예외처리
#### try/catch
* 호출할 메소드에서 예외와 관련된 일이 일어날 수 있다는 것을 알고 있음을, 그런 예외를 처리할 준비가 되어있음을 컴파일러에 알려주는 역할을 한다.
* 컴파일러에서는 프로그래머가 그 예외를 처리하는 구체적인 방법에는 신경쓰지 않는다. 예외를 처리할 것이라는 것만 밝혀주면 문제가 발생하지 않는다.
* try/catch 사이에 다른 코드는 집어넣을 수 없다.

#### 예외(Exception)
* 메소드에서 Exception을 던질 때는 throw 키워드 사용
* throw 키워드의 뜻은 메소드를 만들 때 컴파일러에서 확인하는 예외를 던질 수 있다고 선언하는 것이다.

#### try/catch에서의 RuntimeException
* 컴파일러에서는 RuntimeException을 확장한 예외 클래스는 모두 통과한다.
* RuntimeException은 선언하지 않아도 되고, try/catch를 따로 쓸 필요 X

#### finally
* try 또는 catch문에 return 선언문이 있어도 finally 블록은 실행된다.
* try 뒤에 catch 없이 finally문은 넣을 수 없다.

### 예외와 다형성
* 예외의 장점 : 메소드에서 그 메소드에서 던질 가능성이 있는 모든 예외를 명시적으로 선언하지 않아도 된다.
→ 던지고자 하는 예외의 상위클래스 유형을 이용하여 예외를 선언할 수 있다.
ex) RuntimeException은 Exception 클래스를 상속받는다. 그러면 Exception에 대해서 try/catch문을 선언해도 RuntimeException까지 잡을 수 있다.
* 따로 처리해야 하는 예외에 대해서는 별도의 catch 블록을 만들면 된다.
* catch 블록을 여러 개 사용할 때는 작은 것부터 큰 것으로 나열해야 한다.
* 테스트 과정을 제외하면 Exception에 대한 catch문을 만드는 일은 거의 없을 것이다.
